name: update remote versions
on: 
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: remote query
        run: python $GITHUB_WORKSPACE/.github/workflows/vers_update.py -p $GITHUB_WORKSPACE

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          commit_message: Auto update GitHub Pages latest versions file
          branch: gh-pages
