# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Build Tagmechanic plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@main
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-test-build
        restore-keys: |
            ${{ runner.os }}-pip-test-build
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 buildplugin
        flake8 .
    - name: Build Plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y qttools5-dev-tools
        python buildplugin --language
    - uses: actions/upload-artifact@v2
      with:
        name: tagmech-artifact
        path: ./*.zip
